vpcId: ${vpc_id}
podDisruptionBudget.maxUnavailable: 1
tolerations:
- key: "devopsMangement"
  operator: "Exists"
  effect: "NoSchedule"
nodeSelector:
  system: sdo
  manage-team: devops
  namespace: kube-system
