controller:
  nodeSelector:
    system: sdo
    manage-team: devops
    namespace: kube-system
  tolerations:
  - key: "devopsMangement"
    operator: "Exists"
    effect: "NoSchedule"
  metrics:
    enabled: true

dashboard:
  enabled: ${enable_dashboard}
  nodeSelector:
    system: sdo
    manage-team: devops
    namespace: kube-system
  tolerations:
  - key: "devopsMangement"
    operator: "Exists"
    effect: "NoSchedule"
  ingress:
    enabled: ${ingress_enabled}
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/certificate-arn: ${ingress_certs_arn}
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/healthcheck-port: 3100
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/load-balancer-name: ${ingress_name}
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/ssl-policy: ${ingress_ssl_policy}
      alb.ingress.kubernetes.io/subnets: ${ingress_subnets}
      alb.ingress.kubernetes.io/tags: ${ingress_tags}
      alb.ingress.kubernetes.io/target-type: ip

