nameOverride: kube-dns-autoscaler

        # Formula for controlling the replicas. Adjust according to your needs
        # replicas = max( ceil( cores * 1/coresPerReplica ) , ceil( nodes * 1/nodesPerReplica ) )
config:
  linear:
    coresPerReplica: 256
    nodesPerReplica: 16
    min: 1
    max: 100
    preventSinglePointFailure: true
    includeUnschedulableNodes: true

# Target to scale. In format: deployment/*, replicationcontroller/* or replicaset/* (not case sensitive).
options:
  target: deployment/coredns # Notice the target as `deployment/coredns`

serviceAccount:
  create: true
  name: kube-dns-autoscaler

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
    supplementalGroups: [65534]
    fsGroup: 65534

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

tolerations:
- key: "devopsMangement"
  operator: "Exists"
  effect: "NoSchedule"
